name: erl_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  lottie: ^3.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.9
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  shared_preferences: ^2.0.18
  flutter_svg: ^1.1.6
  rive: ^0.13.17
  flutter_native_splash: ^2.0.7
  image_picker: ^0.8.6
  path: ^1.8.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.8.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Correct placement of assets section
  assets:
    - assets/Images/Google.png
    - assets/Images/apple.png
    - assets/Images/superApp.png
    - assets/Images/superApp_cropped.png
    - assets/Images/blue_bg.jpg
    - assets/Images/white_bg.jpg
    - assets/Images/profile_pic.png
    - assets/Images/dummyActivity.png
    - assets/Images/dummyBanner/dummyBanner.png
    - assets/Images/dummyBanner/dummyBanner1.png
    - assets/Images/dummyBanner/dummyBanner2.png
    - assets/Images/dummyBanner/dummyBanner3.png
    - assets/Images/CarouselSliderVertical/membacaBuku.png
    - assets/Images/CarouselSliderVertical/membeliBuku.png
    - assets/Images/CarouselSliderVertical/mengajar.png
    - assets/Images/CarouselSliderVertical/nilai.png
    - assets/Images/CarouselSliderVertical/ujian.png
    - assets/Images/rekomendasiAplikasi/elib.jpg
    - assets/Images/rekomendasiAplikasi/ebook.jpg
    - assets/Images/rekomendasiAplikasi/erklika.jpg
    - assets/Images/rekomendasiAplikasi/assesment.jpg
    - assets/RiveAssets/

    - assets/icons/apple_box.svg
    - assets/icons/help.svg
    - assets/icons/check.svg
    - assets/icons/code.svg
    - assets/icons/envelope.svg
    - assets/icons/facebook.svg
    - assets/icons/globe.svg
    - assets/icons/home.svg
    - assets/icons/instagram.svg
    - assets/icons/search.svg
    - assets/icons/settings.svg
    - assets/icons/phone-call.svg
    - assets/icons/marker.svg
    - assets/icons/signOut.svg
    - assets/icons/apk.svg
    - assets/icons/language.svg
    - assets/icons/trash.svg
    - assets/icons/keamanan.svg
    - assets/icons/credit_card.svg
    - assets/icons/promo.svg
    - assets/icons/transaksi.svg
    - assets/icons/ask.svg
    - assets/icons/download.svg
    - assets/icons/speaker.svg

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600

    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/Images/superApp.png
  color: "#FBF8EF"
